-- Chạy toàn bộ đoạn này trong Supabase SQL Editor.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  cccd text,
  address text,
  note text,
  latitude double precision,
  longitude double precision,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.customers enable row level security;

drop policy if exists "logged users can read customers" on public.customers;
create policy "logged users can read customers"
on public.customers for select
to authenticated
using (true);

drop policy if exists "logged users can insert customers" on public.customers;
create policy "logged users can insert customers"
on public.customers for insert
to authenticated
with check (true);

drop policy if exists "logged users can update customers" on public.customers;
create policy "logged users can update customers"
on public.customers for update
to authenticated
using (true)
with check (true);

drop policy if exists "logged users can delete customers" on public.customers;
create policy "logged users can delete customers"
on public.customers for delete
to authenticated
using (true);

create index if not exists customers_phone_idx on public.customers(phone);
create index if not exists customers_name_idx on public.customers(name);